##----------------------------------------------
## Hemfile pipeline for cluster wide services
##----------------------------------------------
---
include:
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'terraform/terraform.yaml'
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'environments.yaml'

stages:
  - terraform-init
  - terraform-plan
  - terraform-apply

##-------------------------
## prod environment
##-------------------------
terraform-init:
  extends:
    - .terraform-init
    - .env-gitops-prod
  stage: terraform-init
  environment:
    name: "gitops-prod"

terraform-plan:
  extends:
    - .terraform-plan
    - .env-gitops-prod
  stage: terraform-plan
  environment:
    name: "gitops-prod"

terraform-apply:
  extends:
    - .terraform-apply
    - .env-gitops-prod
  stage: terraform-apply
  environment:
    name: "gitops-prod"
  only:
    - main
  when:
    manual


