##----------------------------------------------
## Hemfile pipeline for cluster wide services
##----------------------------------------------
---
include:
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'terraform/terraform.yaml'
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'environments.yaml'

stages:
  - terraform-plan
  - terraform-apply

variables:
  TF_ROOT: ${CI_PROJECT_DIR} 

cache:
  key: "${TF_ROOT}"
  paths:
    - ${TF_ROOT}/.terraform/

##-------------------------
## dev environment
##-------------------------
terraform-plan-dev:
  extends:
    - .terraform-plan
    - .env-gitops-dev
  stage: terraform-plan
  environment:
    name: "gitops-dev"

terraform-apply-dev:
  extends:
    - .terraform-apply
    - .env-gitops-dev
  stage: terraform-apply
  environment:
    name: "gitops-dev"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "trigger"
      when: always
    - when: manual

##-------------------------
## prod environment
##-------------------------
terraform-plan-prod:
  extends:
    - .terraform-plan
    - .env-gitops-prod
  stage: terraform-plan
  environment:
    name: "gitops-prod"

terraform-apply-prod:
  extends:
    - .terraform-apply
    - .env-gitops-prod
  stage: terraform-apply
  environment:
    name: "gitops-prod"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "trigger"
      when: always
    - when: manual
