##----------------------------------------------
## Microservices Docker Image pipeline
##----------------------------------------------
---
# In order to preserve SHA between builds, we use DinD
include:
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'variables.yaml'

services:
  - name: docker:20.10-dind
    command: ["--mtu=1450"]

# Build and push the image with the specified tag
.build:
  image: docker:20.10
  before_script:
    - until docker info; do sleep 2; done
  script: |-
    set -eu pipefail;
    export TAG=$(cat ./tag);
    docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    cd $DOCKER_CONTEXT || true
    docker build \
      --network host \
      -t registry.gitlab.com/training-gitops/microservices/microservices-demo/$IMAGE:$TAG \
      -t registry.gitlab.com/training-gitops/microservices/microservices-demo/$IMAGE:latest .
    echo "=> Pushing image $IMAGE:$TAG (latest)"
    docker push registry.gitlab.com/training-gitops/microservices/microservices-demo/$IMAGE:$TAG
    docker push registry.gitlab.com/training-gitops/microservices/microservices-demo/$IMAGE:latest
    echo "=> Done"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "push"
      when: never
    - when: always
