##----------------------------------------------
## Hemfile pipeline
##----------------------------------------------
---
include:
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'utils/gpg.yaml'

variables:
  ENV: $ENVIRONMENT
  PROJECT_NAME: ${CI_PROJECT_NAME}

.helm-lint:
  image: $INFRA_IMAGE
  allow_failure: true
  stage: helm-lint
  script:
    - gpg --version
    - sops --version
    - base64 -d $GPG_PRIVATE_KEY | gpg --import
    - sops --verbose -d values.d/gitlab-runner/dev/secrets.yaml
    - helmfile lint

.helm-diff:
  image: $INFRA_IMAGE
  allow_failure: false
  stage: helm-diff
  script:
    - base64 -d $GPG_PRIVATE_KEY | gpg --import
    - helmfile diff --suppress-secrets

.helm-sync:
  image: $INFRA_IMAGE
  allow_failure: false
  stage: helm-sync
  script:
    - base64 -d $GPG_PRIVATE_KEY | gpg --import
    - helmfile sync
