##----------------------------------------------
## Hemfile pipeline
##----------------------------------------------
---
include:
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'utils/gpg.yaml'

variables:
  ENV: $ENVIRONMENT
  PROJECT_NAME: ${CI_PROJECT_NAME}

.helm-lint:
  image: $INFRA_IMAGE
  allow_failure: true
  stage: helm-lint
  script:
    - sops --version
    - echo -e $GPG_PRIVATE_KEY | gpg --import
    - gpg --list-keys
    - helmfile lint

.helm-diff:
  image: $INFRA_IMAGE
  allow_failure: false
  stage: helm-diff
  script: |-
    echo -e $GPG_PRIVATE_KEY | gpg --import
    helmfile diff --suppress-secrets
    echo "ENVIRONMENT: $ENV - NAMESPACE: $KUBE_NAMESPACE"

.helm-sync:
  image: $INFRA_IMAGE
  allow_failure: false
  stage: helm-sync
  script:
    - echo -e $GPG_PRIVATE_KEY | gpg --import
    - helmfile sync
