##----------------------------------------------
## Hemfile pipeline for cluster wide services
##----------------------------------------------
---
include:
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'helm/helmfile.yaml'
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'environments.yaml'
  - project: 'training-gitops/pipeline'
    ref: main
    file: 'linters/yamllint.yaml'

stages:
  - yaml-lint
  - helm-diff
  - helm-sync

variables:
  YAMLLINT_OPTIONS: ""

##-------------------------
## Project linting
##-------------------------
yaml-lint:
  image: python:3.7-alpine
  stage: yaml-lint
  extends:
    .yamllint

##-------------------------
## prod environment
##-------------------------
helm-diff-prod:
  extends:
    - .helm-diff
    - .env-gitops-prod
  stage: helm-diff
  environment:
    name: "gitops-prod"

helm-sync-prod:
  extends:
    - .helm-sync
    - .env-gitops-prod
  stage: helm-sync
  environment:
    name: "gitops-prod"
  only:
    - main
  when:
    manual

##-------------------------
## dev environment
##-------------------------
helm-diff-dev:
  extends:
    - .helm-diff
    - .env-gitops-dev
  stage: helm-diff
  environment:
    name: "gitops-dev"

helm-sync-dev:
  extends:
    - .helm-sync
    - .env-gitops-dev
  stage: helm-sync
  environment:
    name: "gitops-dev"
  only:
    - main
  when:
    manual
